#!/bin/bash
set -e

# ADHD Focus - Self-Hosted Setup Script
# Generates all required secrets and keys for deployment

echo "==================================="
echo "  ADHD Focus - Setup Script"
echo "==================================="
echo ""

# Check if .env already exists
if [ -f ".env" ]; then
  read -p ".env already exists. Overwrite? (y/N): " confirm
  if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
    echo "Setup cancelled."
    exit 0
  fi
fi

# Generate secrets
echo "Generating secrets..."
POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=')
JWT_SECRET=$(openssl rand -base64 32)
SECRET_KEY_BASE=$(openssl rand -base64 64)

# Generate Supabase keys (JWTs)
# These are JWTs signed with JWT_SECRET
echo "Generating Supabase API keys..."

# Check if jwt-cli is available, otherwise use Node.js or Python
generate_jwt() {
  local role=$1
  local secret=$2

  # Try Node.js first (most common)
  if command -v node &> /dev/null; then
    node -e "
const crypto = require('crypto');

const header = { alg: 'HS256', typ: 'JWT' };
const payload = {
  role: '$role',
  iss: 'supabase',
  iat: Math.floor(Date.now() / 1000),
  exp: Math.floor(Date.now() / 1000) + (10 * 365 * 24 * 60 * 60) // 10 years
};

const base64url = (obj) => Buffer.from(JSON.stringify(obj))
  .toString('base64')
  .replace(/=/g, '')
  .replace(/\+/g, '-')
  .replace(/\//g, '_');

const headerB64 = base64url(header);
const payloadB64 = base64url(payload);
const signature = crypto
  .createHmac('sha256', '$secret')
  .update(headerB64 + '.' + payloadB64)
  .digest('base64')
  .replace(/=/g, '')
  .replace(/\+/g, '-')
  .replace(/\//g, '_');

console.log(headerB64 + '.' + payloadB64 + '.' + signature);
"
  # Fallback to Python
  elif command -v python3 &> /dev/null; then
    python3 -c "
import base64
import hmac
import hashlib
import json
import time

def base64url(data):
    return base64.urlsafe_b64encode(json.dumps(data).encode()).decode().rstrip('=')

header = {'alg': 'HS256', 'typ': 'JWT'}
payload = {
    'role': '$role',
    'iss': 'supabase',
    'iat': int(time.time()),
    'exp': int(time.time()) + (10 * 365 * 24 * 60 * 60)
}

header_b64 = base64url(header)
payload_b64 = base64url(payload)
signature = hmac.new(
    '$secret'.encode(),
    (header_b64 + '.' + payload_b64).encode(),
    hashlib.sha256
).digest()
signature_b64 = base64.urlsafe_b64encode(signature).decode().rstrip('=')

print(header_b64 + '.' + payload_b64 + '.' + signature_b64)
"
  else
    echo "ERROR: Need Node.js or Python3 to generate JWT keys" >&2
    exit 1
  fi
}

ANON_KEY=$(generate_jwt "anon" "$JWT_SECRET")
SERVICE_ROLE_KEY=$(generate_jwt "service_role" "$JWT_SECRET")

# Create .env file
echo "Creating .env file..."

cat > .env << EOF
# ADHD Focus - Self-Hosted Configuration
# Generated by setup.sh on $(date)

# ===================
# Database
# ===================
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=postgres
POSTGRES_PORT=5432

# ===================
# JWT & Auth
# ===================
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY=3600

# Supabase API Keys (auto-generated)
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

# Secret for Realtime
SECRET_KEY_BASE=${SECRET_KEY_BASE}

# ===================
# URLs
# ===================
API_EXTERNAL_URL=http://localhost:8000
SITE_URL=http://localhost:3000
ADDITIONAL_REDIRECT_URLS=

# Ports
API_EXTERNAL_PORT=8000
API_EXTERNAL_SSL_PORT=8443
STUDIO_PORT=3000

# ===================
# Email (SMTP)
# ===================
# Configure for email verification/password reset
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_ADMIN_EMAIL=admin@example.com
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=true

# ===================
# Registration
# ===================
DISABLE_SIGNUP=false

# ===================
# Integrations (Optional)
# ===================

# Telegram Bot - Create with @BotFather
TELEGRAM_BOT_TOKEN=

# Google Calendar - Create OAuth app in Google Cloud Console
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# ===================
# Studio
# ===================
STUDIO_DEFAULT_ORGANIZATION=ADHD Focus
STUDIO_DEFAULT_PROJECT=adhd-focus
EOF

chmod 600 .env

echo ""
echo "==================================="
echo "  Setup Complete!"
echo "==================================="
echo ""
echo "Generated secrets:"
echo "  - POSTGRES_PASSWORD: ****"
echo "  - JWT_SECRET: ****"
echo "  - ANON_KEY: ${ANON_KEY:0:20}..."
echo "  - SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY:0:20}..."
echo ""
echo "Next steps:"
echo "  1. (Optional) Edit .env to configure SMTP and integrations"
echo "  2. Run: docker compose up -d"
echo "  3. Access Studio: http://localhost:3000"
echo "  4. API endpoint: http://localhost:8000"
echo ""
echo "For production, also:"
echo "  - Change API_EXTERNAL_URL to your domain"
echo "  - Set up HTTPS (reverse proxy recommended)"
echo "  - Configure SMTP for email verification"
echo ""
